### ISSUE TITLE
执行扫描就失败了

### ISSUE THREAD

**Issue by luwikes** [LangziFun/LangSrcCurise#14]
Traceback (most recent call last):
  File "manage.py", line 48, in <module>
    from core.Run_Tasks import start
  File "/learn/python/LangSrcCurise/core/Run_Tasks.py", line 2, in <module>
    from .main import Sub_Crawl,Sub_Baidu,Sub_Brute,Run_Cpu_Min,Sub_ChangeIp,Sub_ChangeInf,Sub_Api,Heartbeat
  File "/learn/python/LangSrcCurise/core/main.py", line 5, in <module>
    from core.Subdomain_Baidu import Baidu
  File "/learn/python/LangSrcCurise/core/Subdomain_Baidu.py", line 28, in <module>
    Set = Setting.objects.all()[0]
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

**Comment by LangziFun** [comment]
没有设置扫描配置
