### ISSUE TITLE
新建容器，成功安装后，启动扫描后如下报错

### ISSUE THREAD

**Issue by kesonn** [LangziFun/LangSrcCurise#20]
![image](https://user-images.githubusercontent.com/36539433/71637997-6a61e480-2c8e-11ea-92db-89a94f9860b4.png)
`
Traceback (most recent call last):
  File "manage.py", line 50, in <module>
    from core.Run_Tasks import start
  File "/LangSrcCurise/core/Run_Tasks.py", line 2, in <module>
    from .main import Sub_Crawl,Sub_Baidu,Sub_Brute,Run_Cpu_Min,Sub_ChangeIp,Sub_ChangeInf,Sub_Api,Heartbeat
  File "/LangSrcCurise/core/main.py", line 5, in <module>
    from core.Subdomain_Baidu import Baidu
  File "/LangSrcCurise/core/Subdomain_Baidu.py", line 37, in <module>
    Set = Setting.objects.all()[0]
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
`

**Comment by LangziFun** [comment]
亲在后台设置扫描策略就好了
