### ISSUE TITLE
执行python3 manage.py initial出错

### ISSUE THREAD

**Issue by ggwshk** [LangziFun/LangSrcCurise#28]
Traceback (most recent call last):
  File "manage.py", line 46, in <module>
    from initialize.initialdomains import initialdomains
  File "/usr/local/lib/python3.6/site-packages/django/LangSrcCurise/initialize/initialdomains.py", line 12, in <module>
    from core.main import Add_Data_To_Url
  File "/usr/local/lib/python3.6/site-packages/django/LangSrcCurise/core/main.py", line 5, in <module>
    from core.Subdomain_Baidu import Baidu
  File "/usr/local/lib/python3.6/site-packages/django/LangSrcCurise/core/Subdomain_Baidu.py", line 37, in <module>
    Set = Setting.objects.all()[0]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

运行python3 manage.py  scanstart也会报类似的No module的提示
安装的python.3.6.9、django2.1.10
求解[哭]

**Comment by LangziFun** [comment]
这个时候您只需要现在后台设置扫描策略即可呢~

**Comment by ggwshk** [comment]
谢谢大佬，的确配完策略，一切OK了
