### ISSUE TITLE
问一下python3 manage.py startscan   IndexError: list index out of range是什么问题，是哪里越界了

### ISSUE THREAD

**Issue by summerxxoo** [LangziFun/LangSrcCurise#31]
Traceback (most recent call last):
  File "manage.py", line 50, in <module>
    from core.Run_Tasks import start
  File "/Users/xxx/Downloads/LangSrcCurise/core/Run_Tasks.py", line 2, in <module>
    from .main import Sub_Crawl,Sub_Baidu,Sub_Brute,Run_Cpu_Min,Sub_ChangeIp,Sub_ChangeInf,Sub_Api,Heartbeat
  File "/Users/xxxx/Downloads/LangSrcCurise/core/main.py", line 5, in <module>
    from core.Subdomain_Baidu import Baidu
  File "/Users/xxxx/Downloads/LangSrcCurise/core/Subdomain_Baidu.py", line 37, in <module>
    Set = Setting.objects.all()[0]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

**Comment by LangziFun** [comment]
因为您没有设置扫描策略呢
