### ISSUE TITLE
python manage.py initial报错

### ISSUE THREAD

**Issue by Jadore147258369** [LangziFun/LangSrcCurise#51]
C:\Users\Administrator\Desktop\LangSrcCurise>python manage.py initial
Traceback (most recent call last):
  File "manage.py", line 50, in <module>
    from initialize.initialdomains import initialdomains
  File "C:\Users\Administrator\Desktop\LangSrcCurise\initialize\initialdomains.py", line 12, in <module>
    from core.main import Add_Data_To_Url,close_old_connections
  File "C:\Users\Administrator\Desktop\LangSrcCurise\core\main.py", line 5, in <module>
    from core.Subdomain_Baidu import Baidu
  File "C:\Users\Administrator\Desktop\LangSrcCurise\core\Subdomain_Baidu.py", line 37, in <module>
    Set = Setting.objects.all()[0]
  File "C:\Program Files\Python36\lib\site-packages\django\db\models\query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

**Comment by Jadore147258369** [comment]
已解决，需要先添加一条监控记录
