### ISSUE TITLE
运行scan以后mysql报错不能登录

### ISSUE THREAD

**Issue by 211guns** [LangziFun/LangSrcCurise#7]
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    with co_mysql(db='mysql') as cursor:
  File "/usr/local/python3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "manage.py", line 21, in co_mysql
    conn = pymysql.connect(host=host,user=username,password=password,port=port,db=db,charset='utf8')
  File "/usr/local/python3/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

登录mysql报错
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)

**Comment by LangziFun** [comment]
Linux下无法连接MYSQL数据库，原因出在你的linux环境配置上
